apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-data
  labels:
    app: doctors-data
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctors-data
  template:
    metadata:
      labels:
        app: doctors-data
        tier: backend
    spec:
      containers:
      - name: doctors-data
        image: ahermani/doctors:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: doctors-data
  labels:
    app: doctors-data
    tier: doctorsrest
spec:
  selector:
      app: doctors-data
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: patients-data
  labels:
    app: patients-data
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patients-data
  template:
    metadata:
      labels:
        app: patients-data
        tier: backend
    spec:
      containers:
      - name: patients-data
        image: ahermani/patients:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: patients-data
  labels:
    app: patients-data
    tier: patientsrest
spec:
    selector:
      app: patients-data
    type: ClusterIP
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-appointments
  labels:
    app: data-appointments
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-appointments
  template:
    metadata:
      labels:
        app: data-appointments
        tier: backend
    spec:
      containers:
      - name: data-appointments
        image: mkowal17/uaim_proj_appointments
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: data-appointments
  labels:
    app: data-appointments
    tier: appointmentsrest
spec:
  selector:
      app: data-appointments
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-treatments
  labels:
    app: data-treatments
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-treatments
  template:
    metadata:
      labels:
        app: data-treatments
        tier: backend
    spec:
      containers:
      - name: data-treatments
        image: mkowal17/uaim_proj_treatments
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: data-treatments
  labels:
    app: data-treatments
    tier: treatmentsrest
spec:
  selector:
      app: data-treatments
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-specializations
  labels:
    app: data-specializations
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-specializations
  template:
    metadata:
      labels:
        app: data-specializations
        tier: backend
    spec:
      containers:
      - name: data-specializations
        image: mkowal17/uaim_proj_specializations
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: data-specializations
  labels:
    app: data-specializations
    tier: specializationssrest
spec:
  selector:
      app: data-specializations
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-app
  labels:
    app: patient-app
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-app
  template:
    metadata:
      labels:
        app: patient-app
        tier: backend
    spec:
      containers:
      - name: patient-app
        image: ahermani/patient-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: patient-app-service
  labels:
    app: patient-app
    tier: patientsrest
spec:
  selector:
    app: patient-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30005
---